version: '3.4'

services:
  loottables.api:
    image: ${DOCKER_REGISTRY-}loottablesapi
    build:
      context: .
      dockerfile: src/LootTables.API/Dockerfile
    env_file:
    - '.env.prod'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "80"

  mongo.db:
    env_file:
    - '.env.prod'