version: '3.4'

services:
  mongo.db:
    container_name: mongoDB
    image: mongo
    restart: always
    env_file:
    - '.env.dev'
    ports:
    - '27017:27017'
    volumes:
    - mongo-data:/data/db

volumes:
  mongo-data: