version: '3.4'

services:
  #loottables.api:
  #  image: ${DOCKER_REGISTRY-}loottablesapi
  #  build:
  #    context: .
  #    dockerfile: src/LootTables.API/Dockerfile
  #  env_file:
  #  - '.env.dev'
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development

  mongo.db:
    image: mongo
    restart: always
    env_file:
    - '.env.dev'
    ports:
    - '27017:27017'
    volumes:
    - mongo-data:/data/db

volumes:
  mongo-data: